version: "3"
services:
  db:
    image: "postgres"
    container_name: "postgres-container"
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
    ports:
      - "54320:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data